name: ELootchests
version: 1.0-Alpha
main: com.Aiden.net.Elivius.eLootChests.LootChests
api-version: 1.21
authors: [Aiden Rafferty]
description: A plugin that spawns loot chests with random loot
depend: [DecentHolograms]

# ========== COMMANDS ==========
commands:
  eloot:
    description: Main command for loot chests
    usage: /eloot <wand|spawn|despawn|table|new|info|edit>
    permission: eloot.use
    permission-message: You don't have permission to use this command!
    aliases: [lootchest]

# ========== PERMISSIONS ==========
permissions:
  # Base use permission
  eloot.use:
    description: Allows using eloot commands
    default: op

  # Command-specific permissions
  eloot.wand.use:
    description: Allows using the wand tool
    default: op
  eloot.spawn.use:
    description: Allows spawning loot chests
    default: op
  eloot.despawn.use:
    description: Allows despawning loot chests
    default: op
  eloot.table.use:
    description: Allows modifying loot tables
    default: op
  eloot.new.use:
    description: Allows creating new boss groups
    default: op
  eloot.info.use:
    description: Allows viewing group information
    default: op
  eloot.edit.use:
    description: Allows editing group configurations
    default: op
  eloot.test.use:
    description: Allows testing commands
    default: op

  # Admin permission (includes all)
  eloot.admin:
    description: All admin permissions
    default: op
    children:
      eloot.use: true
      eloot.wand.use: true
      eloot.spawn.use: true
      eloot.despawn.use: true
      eloot.table.use: true
      eloot.new.use: true
      eloot.info.use: true
      eloot.edit.use: true
      eloot.test.use: true
      eloot.reload.use: true
