name: ELootchests
version: 1.0-Alpha
main: com.Aiden.net.Elivius.eLootchests.LootChests
api-version: 1.21
authors: [Aiden Rafferty]
description: A plugin that spawns loot chests with random loot


commands:
  eloot:
    description: Main command for loot chests
    usage: /eloot <wand|spawn|despawn|table|new|info|edit>
    permission: eloot.use
    permission-message: You don't have permission to use this command!


permissions:
  eloot.use:
    description: Allows using eloot commands
    default: op
  eloot.wand.use:
    description: Allows using the wand tool
    default: op